global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'restserver'
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  scrape_interval: 5s

  metrics_path: '/prometheus'
  static_configs:
    - targets: ['host.docker.internal:9005']

- job_name: 'promscale'
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  scrape_interval: 5s

  metrics_path: '/metrics'
  static_configs:
    - targets: ['postgresql_exporter:9187']



remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"